namespace NF.Tool.ExcelFlow.Common.Model;

public sealed class ExcelFlowConfig
{
    // TODO(pyoung): filename pattern
    // TODO(pyoung): t4 include path
    // TODO(pyoung): line ending
    public string[] InputPaths { get; set; } = [];
    public string Namespace { get; set; } = "AutoGenerated";
    public string TemplatePath { get; set; } = string.Empty;

    public ExcelFlowConfig_Codegen Codegen { get; set; } = new ExcelFlowConfig_Codegen();
    public ExcelFlowConfig_Db Db { get; set; } = new ExcelFlowConfig_Db();

    public static ExcelFlowConfig Default()
    {
        return new ExcelFlowConfig
        {
            //TemplatePath = "D:\\@NF\\nf-data-flow-2\\NF.Tool.ExcelFlow\\NF.Tool.ExcelFlow.CLI\\_embedded\\Template.t4",
        };
    }
}

public sealed class ExcelFlowConfig_Codegen
{
    public string OutputDirectory { get; set; } = string.Empty;
}

public sealed class ExcelFlowConfig_Db
{
    public string OutputDatabasePath { get; set; } = string.Empty;
}