namespace NF.Tool.ExcelFlow.Common.Model;

public sealed class ExcelFlowConfig : IExcelFlowConfig
{
    // TODO(pyoung): filename pattern
    // TODO(pyoung): t4 include path
    // TODO(pyoung): line ending
    public string[] InputPaths { get; set; } = [];
    public string Namespace { get; set; } = "AutoGenerated";
    public string TemplatePath { get; set; } = string.Empty;
    public E_PART Part { get; set; } = E_PART.BOTH;

    public ExcelFlowConfig_Codegen Codegen { get; set; } = new ExcelFlowConfig_Codegen();
    public ExcelFlowConfig_Sqlite Sqlite { get; set; } = new ExcelFlowConfig_Sqlite();

    public static ExcelFlowConfig Default()
    {
        return new ExcelFlowConfig { };
    }
}

public sealed class ExcelFlowConfig_Codegen : IExcelFlowConfig_Codegen
{
    public string Output { get; set; } = "outdir";
    public bool IsCheckCompilable { get; set; } = false;
}

public sealed class ExcelFlowConfig_Sqlite : IExcelFlowConfig_Sqlite
{
    public string Output { get; set; } = "out.db";
}

public interface IExcelFlowConfig
{
    public string[] InputPaths { get; set; }
    public string Namespace { get; set; }
    public string TemplatePath { get; set; }
    public E_PART Part { get; set; }
}

public interface IExcelFlowConfig_Codegen
{
    public string Output { get; set; }
    public bool IsCheckCompilable { get; set; }
}

public interface IExcelFlowConfig_Sqlite
{
    public string Output { get; set; }
}
